sudo: required
services:
  - docker

before_install:
  - docker build -t ${DOCKER_ID}/multi-container-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -t ${DOCKER_ID}/multi-container-test npm test -- --coverage

after_success:
  - docker build -t ${DOCKER_ID}/multi-client ./client
  - docker build -t ${DOCKER_ID}/multi-nginx ./nginx
  - docker build -t ${DOCKER_ID}/multi-worker ./worker
  - docker build -t ${DOCKER_ID}/multi-server ./server
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ${DOCKER_ID}/multi-client
  - docker push ${DOCKER_ID}/multi-nginx
  - docker push ${DOCKER_ID}/multi-worker
  - docker push ${DOCKER_ID}/multi-server

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: docker-multi
  env: DockerMulti-env
  bucket_name: $BUCKET_NAME
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
